# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:clickguard/api-models
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'ubuntu'
  args: ['bash', './prebuild.sh', '${_ENV}']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cg-platform:$TAG_NAME', '.']
images:
- 'gcr.io/$PROJECT_ID/cg-platform:$TAG_NAME'
timeout: 1200s
availableSecrets:
  secretManager:
  - versionName: projects/clickguard-app/secrets/github-deploy-key/versions/latest
    env: 'SSH_KEY'